load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "greetings",
    srcs = ["greetings.go"],
    importpath = "GO-BUILD-WITH-BAZEL/com/saif/hello-world/greetings",
    visibility = ["//visibility:public"],
)
